# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CallRatioSpreadBarrier <- function(is_bull, expiry, strike1, strike2, spot, vol, r, d, number_of_paths, number_of_dates, is_double_barrier, is_knock_out, barrier1, barrier_direction, barrier2, tolerance, ratio) {
    .Call(`_CallSpreadBarrierPrice_CallRatioSpreadBarrier`, is_bull, expiry, strike1, strike2, spot, vol, r, d, number_of_paths, number_of_dates, is_double_barrier, is_knock_out, barrier1, barrier_direction, barrier2, tolerance, ratio)
}

