// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CallSpreadBarrierSpread
double CallSpreadBarrierSpread(int is_bull, double expiry, double strike1, double strike2, double spot, double vol, double r, double d, int number_of_paths, int number_of_dates, int is_double_barrier, int is_knock_out, double barrier1, int barrier_direction, double barrier2, double tolerance);
RcppExport SEXP _CallSpreadBarrierPrice_CallSpreadBarrierSpread(SEXP is_bullSEXP, SEXP expirySEXP, SEXP strike1SEXP, SEXP strike2SEXP, SEXP spotSEXP, SEXP volSEXP, SEXP rSEXP, SEXP dSEXP, SEXP number_of_pathsSEXP, SEXP number_of_datesSEXP, SEXP is_double_barrierSEXP, SEXP is_knock_outSEXP, SEXP barrier1SEXP, SEXP barrier_directionSEXP, SEXP barrier2SEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type is_bull(is_bullSEXP);
    Rcpp::traits::input_parameter< double >::type expiry(expirySEXP);
    Rcpp::traits::input_parameter< double >::type strike1(strike1SEXP);
    Rcpp::traits::input_parameter< double >::type strike2(strike2SEXP);
    Rcpp::traits::input_parameter< double >::type spot(spotSEXP);
    Rcpp::traits::input_parameter< double >::type vol(volSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_paths(number_of_pathsSEXP);
    Rcpp::traits::input_parameter< int >::type number_of_dates(number_of_datesSEXP);
    Rcpp::traits::input_parameter< int >::type is_double_barrier(is_double_barrierSEXP);
    Rcpp::traits::input_parameter< int >::type is_knock_out(is_knock_outSEXP);
    Rcpp::traits::input_parameter< double >::type barrier1(barrier1SEXP);
    Rcpp::traits::input_parameter< int >::type barrier_direction(barrier_directionSEXP);
    Rcpp::traits::input_parameter< double >::type barrier2(barrier2SEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(CallSpreadBarrierSpread(is_bull, expiry, strike1, strike2, spot, vol, r, d, number_of_paths, number_of_dates, is_double_barrier, is_knock_out, barrier1, barrier_direction, barrier2, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CallSpreadBarrierPrice_CallSpreadBarrierSpread", (DL_FUNC) &_CallSpreadBarrierPrice_CallSpreadBarrierSpread, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_CallSpreadBarrierPrice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
